#
# Autogenerated by Thrift Compiler (0.16.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys

from thrift.transport import TTransport
all_structs = []


class DeviceStatus(object):
    """
    Attributes:
     - measurement_status
     - ready_status
     - transfer_status
     - error_status

    """


    def __init__(self, measurement_status=None, ready_status=None, transfer_status=None, error_status=None,):
        self.measurement_status = measurement_status
        self.ready_status = ready_status
        self.transfer_status = transfer_status
        self.error_status = error_status

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.BYTE:
                    self.measurement_status = iprot.readByte()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.BOOL:
                    self.ready_status = iprot.readBool()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.BYTE:
                    self.transfer_status = iprot.readByte()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.BYTE:
                    self.error_status = iprot.readByte()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('DeviceStatus')
        if self.measurement_status is not None:
            oprot.writeFieldBegin('measurement_status', TType.BYTE, 1)
            oprot.writeByte(self.measurement_status)
            oprot.writeFieldEnd()
        if self.ready_status is not None:
            oprot.writeFieldBegin('ready_status', TType.BOOL, 2)
            oprot.writeBool(self.ready_status)
            oprot.writeFieldEnd()
        if self.transfer_status is not None:
            oprot.writeFieldBegin('transfer_status', TType.BYTE, 3)
            oprot.writeByte(self.transfer_status)
            oprot.writeFieldEnd()
        if self.error_status is not None:
            oprot.writeFieldBegin('error_status', TType.BYTE, 4)
            oprot.writeByte(self.error_status)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class DacConfig(object):
    """
    Attributes:
     - t_dwell
     - set_d_setup
     - set_g_setup
     - dac1Config
     - dac2Config

    """


    def __init__(self, t_dwell=None, set_d_setup=None, set_g_setup=None, dac1Config=None, dac2Config=None,):
        self.t_dwell = t_dwell
        self.set_d_setup = set_d_setup
        self.set_g_setup = set_g_setup
        self.dac1Config = dac1Config
        self.dac2Config = dac2Config

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.t_dwell = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.DOUBLE:
                    self.set_d_setup = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.DOUBLE:
                    self.set_g_setup = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.MAP:
                    self.dac1Config = {}
                    (_ktype1, _vtype2, _size0) = iprot.readMapBegin()
                    for _i4 in range(_size0):
                        _key5 = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                        _val6 = iprot.readDouble()
                        self.dac1Config[_key5] = _val6
                    iprot.readMapEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.MAP:
                    self.dac2Config = {}
                    (_ktype8, _vtype9, _size7) = iprot.readMapBegin()
                    for _i11 in range(_size7):
                        _key12 = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                        _val13 = iprot.readDouble()
                        self.dac2Config[_key12] = _val13
                    iprot.readMapEnd()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('DacConfig')
        if self.t_dwell is not None:
            oprot.writeFieldBegin('t_dwell', TType.I32, 1)
            oprot.writeI32(self.t_dwell)
            oprot.writeFieldEnd()
        if self.set_d_setup is not None:
            oprot.writeFieldBegin('set_d_setup', TType.DOUBLE, 2)
            oprot.writeDouble(self.set_d_setup)
            oprot.writeFieldEnd()
        if self.set_g_setup is not None:
            oprot.writeFieldBegin('set_g_setup', TType.DOUBLE, 3)
            oprot.writeDouble(self.set_g_setup)
            oprot.writeFieldEnd()
        if self.dac1Config is not None:
            oprot.writeFieldBegin('dac1Config', TType.MAP, 4)
            oprot.writeMapBegin(TType.STRING, TType.DOUBLE, len(self.dac1Config))
            for kiter14, viter15 in self.dac1Config.items():
                oprot.writeString(kiter14.encode('utf-8') if sys.version_info[0] == 2 else kiter14)
                oprot.writeDouble(viter15)
            oprot.writeMapEnd()
            oprot.writeFieldEnd()
        if self.dac2Config is not None:
            oprot.writeFieldBegin('dac2Config', TType.MAP, 5)
            oprot.writeMapBegin(TType.STRING, TType.DOUBLE, len(self.dac2Config))
            for kiter16, viter17 in self.dac2Config.items():
                oprot.writeString(kiter16.encode('utf-8') if sys.version_info[0] == 2 else kiter16)
                oprot.writeDouble(viter17)
            oprot.writeMapEnd()
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(DeviceStatus)
DeviceStatus.thrift_spec = (
    None,  # 0
    (1, TType.BYTE, 'measurement_status', None, None, ),  # 1
    (2, TType.BOOL, 'ready_status', None, None, ),  # 2
    (3, TType.BYTE, 'transfer_status', None, None, ),  # 3
    (4, TType.BYTE, 'error_status', None, None, ),  # 4
)
all_structs.append(DacConfig)
DacConfig.thrift_spec = (
    None,  # 0
    (1, TType.I32, 't_dwell', None, None, ),  # 1
    (2, TType.DOUBLE, 'set_d_setup', None, None, ),  # 2
    (3, TType.DOUBLE, 'set_g_setup', None, None, ),  # 3
    (4, TType.MAP, 'dac1Config', (TType.STRING, 'UTF8', TType.DOUBLE, None, False), None, ),  # 4
    (5, TType.MAP, 'dac2Config', (TType.STRING, 'UTF8', TType.DOUBLE, None, False), None, ),  # 5
)
fix_spec(all_structs)
del all_structs
